### ISSUE TITLE
Dlib and face detector

### ISSUE THREAD

**Issue by Skivus** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#1]
Hi. Thanks for change path in node - at now selectable path for dlib. But it still not work:

!!! Exception during processing !!!
Traceback (most recent call last):
  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 328, in run
    return LoadFaceDetectorModel.load_model(model_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 322, in load_model
    face_detector = FaceDetector.dlib.get_frontal_face_detector()
                    ^^^^^^^^^^^^
NameError: name 'FaceDetector' is not defined

![изображение](https://github.com/cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life/assets/39644408/9d3babdd-d447-4ab1-b9e3-456330b4064a)

**Comment by cdb-boop** [comment]
It looks like imports are failing because I removed some requirements accidentally. I've fixed the `requirements.txt` file to fix this.

I've also updated the `README.txt` to address any [installation issues](https://github.com/cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life?tab=readme-ov-file#installation-troubleshooting).

Note that I successfully got it working with a fresh copy of the portable Windows ComfyUI, but feel free ask for help if the linked explanation is unclear or if you are still having issues.

**Comment by Skivus** [comment]
sorry, but i have another problem.
in process install i get next error: 
```
[!]   ERROR: Failed building wheel for dlib
 Failed to build dlib
[!] ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects
install/(de)activation script failed: J:\StableCascade\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life
```
for some reason it's trying to install from cache the version is 19.24.1

but i try another way to install dlib (pip install dlib) - its ok, complete. but the version is 19.24.2

```html

 Installing build dependencies ... done
 Getting requirements to build wheel ... done 
 Preparing metadata (pyproject.toml) ... done
 Building wheels for collected packages: dlib 
 Building wheel for dlib (pyproject.toml) ... done
 Created wheel for dlib: filename=dlib-19.24.2-cp312-cp312-win_amd64.whl size=2847343 sha256=0733315ddb13846d7ad66f614bd6ef3ab89b9b4ec9782453c622c32f51ec17f4
 Stored in directory: c:\users\design\appdata\local\pip\cache\wheels\57\0d\5d\bcacadb519c16109e82f9f143bb5af8f6a4a63aa53a5dba0df <br>
 Successfully built dlib
 Installing collected packages: dlib
 Successfully installed dlib-19.24.2

```


and after this i try install this node from the repo - and get this error and node is not work. 

p.s.: yeah, i know what i dumb and lamer :) I'm sorry :)

**Comment by Skivus** [comment]
>pip list
---
attrs                     23.2.0
cmake                     3.28.3
contourpy                 1.2.0
cycler                    0.12.1
**dlib                      19.24.2**
easydict                  1.13
fonttools                 4.50.0
imageio                   2.34.0
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
lazy_loader               0.3
matplotlib                3.8.3
networkx                  3.2.1
numpy                     1.26.4
opencv-python             4.9.0.80
packaging                 24.0
pillow                    10.2.0
pip                       24.0
pyparsing                 3.1.2
pyproject-toml            0.0.10
python-dateutil           2.9.0.post0
referencing               0.34.0
rpds-py                   0.18.0
scikit-image              0.22.0
scipy                     1.12.0
setuptools                69.2.0
six                       1.16.0
tifffile                  2024.2.12
toml                      0.10.2
wheel                     0.43.0

**Comment by cdb-boop** [comment]
Dlib 19.24.2 should be fine. I just had the requirement as 19.24.1 because that's the one that I was able to get to build on a fluke once.

Does the workflow not run in ComfyUI?

**Comment by Skivus** [comment]
same problem

Error occurred when executing BOPBTL_LoadFaceDetectorModel:

name 'FaceDetector' is not defined

  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 328, in run
    return LoadFaceDetectorModel.load_model(model_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 322, in load_model
    face_detector = FaceDetector.dlib.get_frontal_face_detector()
                    ^^^^^^^^^^^^

**Comment by Skivus** [comment]
i dont understand next:
if i install node (from comfy manager or from command git...) - step, where must be installed dlib is crashed
if i install dlib from command - dlib installed normaly

but node not work

**Comment by Skivus** [comment]
in start comfyui:
File "J:\StableCascade\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\Face_Detection\detect_all_dlib.py", line 15, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'

but in pip list - dlib 19.24.1 (at now, i reinstalled to this version)

**Comment by cdb-boop** [comment]
Are you sure that you are installing with pip to ComfyUI's portable python and not your system's python?

```shell
J:\StableCascade\ComfyUI_windows_portable\python_embeded\python.exe -m pip install easydict matplotlib opencv-python scikit-image scipy

J:\StableCascade\ComfyUI_windows_portable\python_embeded\python.exe -m pip install cmake
J:\StableCascade\ComfyUI_windows_portable\python_embeded\python.exe-m pip install dlib
```

If this doesn't work, then maybe you can try a prebuilt dlib like the ones found [here](https://github.com/z-mahmud22/Dlib_Windows_Python3.x) or [here](https://github.com/sachadee/Dlib), and then install with something like the following:

```shell
J:\StableCascade\ComfyUI_windows_portable\python_embeded\python.exe -m pip install path\to\dlib.whl
```

**Comment by Skivus** [comment]
oh... it seems I have a guess - since I have a portable version, it has its own python. version lower than the one installed on the system (3.11.6). and there really is NO dlib in its libraries.

**Comment by Skivus** [comment]
ooo! its work! thanks for you and sorry for my!
