### ISSUE TITLE
Question for pth files

### ISSUE THREAD

**Issue by szkane** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#10]
```
vae_a
Place in models/vae/.

restoration/VAE_A_quality/latest_net_G.pth

vae_b
Extract the following models and place them inside models/vae/.

restoration/VAE_B_quality/latest_net_G.pth
restoration/VAE_B_scratch/latest_net_G.pth (scratch_detection)

```

which "latest_net_G.pth"  mv to the comfyUI path "model/vae"  ?  All are the some file name, or mv the VAE_XX folder？

**Comment by cdb-boop** [comment]
> which "latest_net_G.pth" mv to the comfyUI path "model/vae"?

If you plan on removing scratches, you need to mv the `VAE_B_scratch` one. I believe the other one doesn't handle scratches.

> All are the some file name, or mv the VAE_XX folder?

You can rename the files or use whatever directory structure you prefer, as they will be selected from a drop-down at runtime.
