### ISSUE TITLE
Error importing nodes

### ISSUE THREAD

**Issue by Hienhuynhduc** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#15]
I keep bumping into missing extension nodes after installing everything as instructed.
Please help me fix these errors.
Thank you!

![Screenshot 2024-08-11 215646](https://github.com/user-attachments/assets/12b464b1-53b6-4f9e-87ac-37533bbb6077)
![Screenshot 2024-08-12 121808](https://github.com/user-attachments/assets/c5689c5e-3281-484f-85ae-6bfcee3cacbc)

**Comment by cdb-boop** [comment]
It looks like you are missing dlib.

You can try installing it like this, making sure you are using your ComfyUI's python.

```shell
.\python_embeded\python.exe -m pip install cmake
.\python_embeded\python.exe -m pip install dlib
```

If this doesn't work, then you can try a prebuilt dlib like the ones found [here](https://github.com/z-mahmud22/Dlib_Windows_Python3.x) or [here](https://github.com/sachadee/Dlib), and then install with something like the following:

```shell
.\python_embeded\python.exe -m pip install path\to\dlib.whl
```

**Comment by Hienhuynhduc** [comment]
Thanks for your quick response. It was my mistake to use installed Python instead of the embed one. Now everything looks perfect. I'm starting to tinker with it right now.
If you have any tutorial for this workflow at hand, please share. It would be much appreciated.
Cheers!

**Comment by cdb-boop** [comment]
No tutorials, but you can always drag the screenshots of the workflows to load them in ComfyUI. Also, there is a nice [workflow with SUPIR](https://openart.ai/workflows/datou/old-photo-restoration-xl/vKtihSX1DGBiBjAovlSP) out there that you could try too.
