### ISSUE TITLE
GPU still being used when device_ids = -1 (CPU)

### ISSUE THREAD

**Issue by TTKyo** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#17]
![Captura de tela 2024-08-21 153947](https://github.com/user-attachments/assets/3c1ff66b-53f5-416a-a17a-9e36f63d896b)

Hi, i tried using the "BOPBTL + Scratch Detection and Face Enhancement (Stages 1-4)" workflow, but i'm getting this error on the "Load Face Enhancer Model" node, device id is set to -1.

 "Load Restore Old Photos" node is fine using -1.

**Comment by cdb-boop** [comment]
Yeah, I suspected that the CPU only mode wasn't working properly.

Before I go deeper, have you tried using the flag `--cpu` when starting ComfyUI?

**Comment by TTKyo** [comment]
Thanks, and i run Comfy with the --cpu flag, it's fine on my SD1.5 workflow.

**Comment by cdb-boop** [comment]
Okay. I've tested it on my end. Can you update the node and try now?

**Comment by TTKyo** [comment]
No bueno, same error. I updated the node by replacing the "\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\Face_Enhancement" folder, do i need do to something else?

**Comment by TTKyo** [comment]
Just tried both methods, same thing. I'm making sure to restart comfy, clearing all nodes and refreshing every try.

**Comment by cdb-boop** [comment]
Okay, I fix the error you showed and fixed the scratch model loader too.

Does it work now?

**Comment by TTKyo** [comment]
YES! Thanks, everything is working fine now.
