### ISSUE TITLE
The model download link seems to be unable to download properly.

### ISSUE THREAD

**Issue by xucanjie** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#2]
https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Global/checkpoints.zip
https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Face_Enhancement/checkpoints.zip

![image](https://github.com/cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life/assets/15358357/853bf8ff-14c2-48e8-b83a-8934d576ebc9)

**Comment by cdb-boop** [comment]
I've filed an issue with the main repo [here](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/294).

@xucanjie If there isn't a response in a reasonable amount of time, I will investigate another way for people to down the weights.

**Comment by xucanjie** [comment]
![image](https://github.com/cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life/assets/15358357/975a616e-5a57-4553-ab25-48c17bd3519b)
https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/releases/download/v1.0/face_checkpoints.zip
unzip face_checkpoints.zip
wget https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/releases/download/v1.0/global_checkpoints.zip
unzip global_checkpoints.zip
Is it these two?

**Comment by cdb-boop** [comment]
Yeah, those look right. Thanks for pointing them out. I'll fix the README.
