### ISSUE TITLE
where is workflow json file,thanks?

### ISSUE THREAD

**Issue by hktalent** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#21]
# where is workflow json file,thanks?
- 1、BOPBTL + Scratch Detection and Face Enhancement (Stages 1-4)
- 2、Face Enhancement (Advanced) (Stages 2-4)
- 3、x4 BOPBTL + Scratch Detection and Face Enhancement (Advanced) (Stages 1-4)
- 4、.....

thanks

**Comment by cdb-boop** [comment]
They are embedded in the images. You can drag the images onto the node graph.
