### ISSUE TITLE
ERROR:operands could not be broadcast together with shapes (449，319.3) (448,3203)

### ISSUE THREAD

**Issue by moosewoler** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#22]
I have encountered "operands could not be broadcast ..." problem while using BOPBTL + Scratch Detection and Face Enhancement (Stages 1-4).

The reason is the shape of the image does not match the shape of the mask.

I have modified the Global/test.py as follow:

![图片](https://github.com/user-attachments/assets/adfb1e5a-f5be-4d3e-a90b-ee8f9729b1de)

Does it OK?

**Comment by cdb-boop** [comment]
Thanks! I updated the node to support this. However, I made the padding mode and related values settings in the node so it is more flexible.
