### ISSUE TITLE
Impossible to load shape_predictor_68_face_landmarks

### ISSUE THREAD

**Issue by diripirate** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#24]
Hello.

I've followed all the steps but the node "Load Face Detector Model (dlib) raises an error:

`Value not in list: shape_predictor_68_face_landmarks: 'dlib\shape_predictor_68_face_landmarks.dat' not in []
`
I've placed the shape_predictor_68_face_landmarks.dat file inside models/facedetection
Also, if I create a new node, the dropdown doesn't work, so ovbiously comfyui is not finding the file

Is there a way to solve this?

I'm using comfyui in windows. Dlib is installed and all the installation steps were sucessful. 

Thank you.

**Comment by cdb-boop** [comment]
Did you try refreshing ComfyUI with the "Refresh" button, reloading the webpage or restarting ComfyUI? If you just added the folder/file, ComfyUI would not know about it.

**Comment by diripirate** [comment]
Yes, I tried refreshing and restarting completly ComfyUI, but same result.

Do I have to add the path to the file: extra_model_paths.yaml?

**Comment by cdb-boop** [comment]
You can try, but it shouldn't need to be. If it is in `models/facedetection/shape_predictor_68_face_landmarks.dat` it should work. The file does end with `.dat`, right? Are there any errors in the command line?

**Comment by cdb-boop** [comment]
If the file is detected, you should be able to select it in the node's dropdown.

**Comment by diripirate** [comment]
It's working now. The problem is that i'm stupid... I extracted the .bz2 but instead of copying the .bat, i copied the .bz2 to the folder.

Now works like charm. Sorry 😅
