### ISSUE TITLE
ERROR: Failed building wheel for dlib

### ISSUE THREAD

**Issue by Mubumbutu** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#25]
Is anyone able to explain to me how I can fix this problem? I can't install ComfyUI-Bringing-Old-Photos-Back-to-Life I have done all the requirements and yet the error keeps popping up, I don't know what to do anymore.... I have Cmake installed, Dlib - manually I also installed, Visual studio with libraries, added path to Cmake. I even changed python versions because someone wrote that on 3.7 there are no problems, but not with me..
![Bez tytułu](https://github.com/user-attachments/assets/d852a496-7bcd-47ab-b3bc-ce0207b79f3c)

**Comment by cdb-boop** [comment]
I'm not sure what is going wrong, but you can always try a prebuilt dlib wheel, like the ones found [here](https://github.com/z-mahmud22/Dlib_Windows_Python3.x) or [here](https://github.com/sachadee/Dlib), and then install with something similar to the following:

```shell
path\to\your\comfyui\python.exe -m pip install path\to\dlib.whl
```

**Comment by Mubumbutu** [comment]
I'm not sure what is going wrong - me too haha

I typed “python --version” - I have 3.7.0 so I downloaded the file dlib-19.22.99-cp37-cp37m-win_amd64.whl, copied it to the python folder and installed it, unfortunately the error continues to show when it wants to install ComfyUI-Bringing-Old-Photos-Back-to-Life via comfyui manager.

![Bez tytułu2](https://github.com/user-attachments/assets/1355d6ec-4925-49af-9881-875df9e1b40c)
![Bez tytułu3](https://github.com/user-attachments/assets/cabf2409-b7f6-4028-8af6-8bca4737dc82)
![Bez tytułu4](https://github.com/user-attachments/assets/cd014564-510b-42f6-a163-86a7d8216b88)
![Bez tytułu](https://github.com/user-attachments/assets/f837e20d-46bf-463f-ac97-a614a9baaefd)

**Comment by cdb-boop** [comment]
Just to make sure, you are installing to the correct python, the one ComfyUI is using?

Can you show me the command line error when you start up ComfyUI and it fails to load the node? It should give me a better idea what is not working.

**Comment by Mubumbutu** [comment]
Oh, now I get it. God bless you for mentioning the keyword! I didn’t realize that ComfyUI uses its own version of Python—I was installing dlib in the wrong place. Rookie mistake. Problem solved, thanks for your time! If you have a moment, could you also explain how to change the Python version in ComfyUI? :)

**Comment by cdb-boop** [comment]
> If you have a moment, could you also explain how to change the Python version in ComfyUI?

I'm not sure, but I'd guess you'd need to delete ComfyUI's venv and then install things manually, as described [here](https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#manual-install-windows-linux). You may run into issue and you'd also have to reinstall all your custom nodes. (I personally use my Conda for my virtual environment, but I have to jump through some hoops to update requirements and start ComfyUI with the Conda enviornment.)

**Comment by jkyx5588** [comment]
pip install dlib-bin
