### ISSUE TITLE
shape_predictor_68_face_landmarks.dat   Where should the correct location of the model file be?

### ISSUE THREAD

**Issue by cheng0009** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#27]
shape_predictor_68_face_landmarks.dat

Where should the correct location of the model file be? I have tried multiple locations and cannot find it when loading the comfuyi interface node. Please help me!

![image](https://github.com/user-attachments/assets/aad90dfc-9c92-4014-a208-86f70a212dee)

**Comment by cdb-boop** [comment]
You need to make a custom folder in `models/facedetection/`.

**Comment by cheng0009** [comment]
![image](https://github.com/user-attachments/assets/80079619-b018-447b-a4b9-87c5ec406cb1)
I have already done so, but the same situation still persists - I cannot find this model in the node. Thank you very much for your answer.

**Comment by cdb-boop** [comment]
Did you refresh the application? It should show up.

**Comment by cheng0009** [comment]
It was my mistake. I migrated all the models in the model folder to another drive letter and put it back in its original drive letter. thank.
