### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Zaldor** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#28]
not clear where to place the downloaded files, should the models be copied with respective subfolder? as they have same name

**Comment by cdb-boop** [comment]
The files can have whatever name and file structure you want. They just need to be in the correct folders (e.g. `vae`, `checkpoints`, `facedetection`) so the nodes can find them. You might have to create the `facedetection` folder manually.

The original project uses the same names for some of the models and keeps them separate by folder, so if you put them in the same folder you'll have to rename them.

https://github.com/cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life?tab=readme-ov-file#2-models
