### ISSUE TITLE
(IMPORT FAILED) [ComfyUI Bringing Old Photos Back to Life]

### ISSUE THREAD

**Issue by yanniniqi** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#29]
安装插件后提示报错
进入工作流：
Missing Node Types
When loading the graph, the following node types were not found
BOPBTL_ScratchMask
BOPBTL_RestoreOldPhotos
BOPBTL_LoadScratchMaskModel
BOPBTL_LoadRestoreOldPhotosModel
怎么解决呢？谢谢

**Comment by cdb-boop** [comment]
Did you install the [requirements](https://github.com/cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life?tab=readme-ov-file#1-requirements)? The nodes won't load if there are python packages missing.
