### ISSUE TITLE
Issues with paths

### ISSUE THREAD

**Issue by fscheps** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#30]
Hi there, I seem to have a lot of issues with paths that seem to be created for Windows but dont work on Mac.
Do you happen to have any Workflow files for Mac? 

I`ve been trying to troubleshoot with ChatGPT but without any luck.

Thank you!

**Comment by cdb-boop** [comment]
Yeah, I don't have a Mac to test it on, so I'm not surprised.

If the issues you are having are with paths, it should be a matter of changing Window's backslashes `\` to forward slashes `/`.

If you can give me the error messages you are running into, I can try and take a look.

**Comment by fscheps** [comment]
Issue Summary

Problem:
ComfyUI is unable to validate certain model file paths when running the “Bringing Old Photos Back to Life” package. The issue stems from Windows-style backslashes (\) being used in the workflow JSON files, which are incompatible with Unix-based systems like macOS and Linux that require forward slashes (/) for file paths.

Detailed Explanation
	1.	Error Messages:
ComfyUI throws errors like this:

Value not in list: vae_a: 'bopbtl\VAE_A_quality\latest_net_G.pth' not in []
Value not in list: face_enhance_model: 'bopbtl\FaceEnhancement\FaceSR_512\latest_net_G.pth' not in []


	2.	Root Cause:
	•	The workflow JSON files (e.g., bopbtl-full-workflow-advanced-512-x4-upscale-round-pad-nearest-16-previews.json) reference paths with backslashes (\), which are the standard for Windows.
	•	On Unix-based systems like macOS or Linux, these backslashes are not recognized correctly, leading to ComfyUI failing to locate the model files.
	3.	Current File Paths in the JSON (Problematic):

"bopbtl\\VAE_A_quality\\latest_net_G.pth",
"bopbtl\\FaceEnhancement\\FaceSR_512\\latest_net_G.pth",
"bopbtl\\scratch_detection\\FT_Epoch_latest.pt",
"dlib\\shape_predictor_68_face_landmarks.dat"


	4.	Correct File Paths for Cross-Platform Compatibility:
Forward slashes (/) should be used instead, as they are supported on both Windows and Unix systems:

"bopbtl/VAE_A_quality/latest_net_G.pth",
"bopbtl/FaceEnhancement/FaceSR_512/latest_net_G.pth",
"bopbtl/scratch_detection/FT_Epoch_latest.pt",
"dlib/shape_predictor_68_face_landmarks.dat"

Proposed Fix

To ensure compatibility across all operating systems:
	1.	Replace all Windows-style backslashes (\) with forward slashes (/) in the workflow JSON files:
	•	For example:
"bopbtl\\VAE_A_quality\\latest_net_G.pth" → "bopbtl/VAE_A_quality/latest_net_G.pth"
	2.	Validate the changes on macOS, Linux, and Windows to ensure the models load correctly.
	3.	Update the repository with the fixed JSON files.

Steps to Reproduce (On macOS or Linux):
	1.	Install ComfyUI and the “Bringing Old Photos Back to Life” package.
	2.	Place all required model files in the correct directories.
	3.	Load the provided workflows (e.g., bopbtl-full-workflow-advanced-512-x4-upscale-round-pad-nearest-16-previews.json).
	4.	Observe the error messages related to file paths not being detected.

Why This Matters

Fixing the file paths improves cross-platform compatibility, allowing users on macOS and Linux to use the package without manual intervention.

**Comment by cdb-boop** [comment]
If the issue you are having is just with the slashes in the nodes, you just need to select the correct models according to the installation instructions in each node's dropdown, using the image as reference.
