### ISSUE TITLE
Unable to download, authorization required???

### ISSUE THREAD

**Issue by wocaozhuaige** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#31]
![微信图片_20241219223332](https://github.com/user-attachments/assets/5338a125-8730-41bb-9b92-1b8292511fea)

The download model shows that it cannot be downloaded. Do you need authorization???

**Comment by cdb-boop** [comment]
Which link is bad?

You can check the main repo to try and find a link to the model. If you can't access it, you might need to file an issue with them. https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life
