### ISSUE TITLE
Is it possible to eliminate the need to install "CMake" on the computer?

### ISSUE THREAD

**Issue by joelandresnavarro** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#5]
Hello, do you think it might not be necessary to install "CMake" on the computer? (I consult it to know the possibility, this node is an excellent tool but I would not like to have to install extra things to my computer directly)

I would appreciate an answer, also great implementation on your part!!!

And if it is possible to do this without "CMake" I would like you to mention it to me, I prefer to use the portable version of ComfyUI because it is portable

**Comment by cdb-boop** [comment]
I could be wrong, but I believe CMake is only needed when locally building/installing the dlib python package.

As stated in the README, you can also use a prebuilt wheel. I'm not sure about the security of using pre-built wheels, but you  can find some, for example, [here](https://github.com/sachadee/Dlib) or [here](https://github.com/z-mahmud22/Dlib_Windows_Python3.x).

Then you should just need to install the requirements to your ComfyUI's python.exe:
```shell
path\to\python.exe -m pip install easydict matplotlib opencv-python scikit-image scipy
```
```shell
path\to\python.exe -m pip install path\to\dlib.whl
```

**Comment by joelandresnavarro** [comment]
It should be run in python_embeded right?

**Comment by cdb-boop** [comment]
`path\to\python.exe` should be the path to your portable ComfyUI's python.

**Comment by joelandresnavarro** [comment]
It has worked well for me, I don't see any problems. The nodes appear. Now I will install the models but I really don't understand how to move them I see many hahaha

It would be good to create a folder dedicated to these nodes in models/ as happens in this custome_node https://github.com/Acly/comfyui-inpaint-nodes

(Just a suggestion, to facilitate the process or be more practical)

Thanks for this tool!
