### ISSUE TITLE
Device ID's - Use -1 for cpu

### ISSUE THREAD

**Issue by RikkB** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#9]
Error occurred when executing BOPBTL_LoadRestoreOldPhotosModel:

Device index must not be negative

**Comment by cdb-boop** [comment]
Okay, I pushed a fix which addresses the error, however, parts of the pipeline may still be using the gpu.

**Comment by RikkB** [comment]
Fixed it for me, thanks
